# Generated by Django 3.2.16 on 2023-02-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errortypessalesopportunities',
            name='errorDescription',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
