# Generated by Django 3.2.16 on 2023-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketing', '0002_errortypessalesopportunities_errordescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvolumemonth',
            name='fiscal_quarter',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvolumemonth',
            name='fiscal_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
