# Generated by Django 3.2.16 on 2023-02-14 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20230214_0332'),
        ('productMarketing', '0003_auto_20230211_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstosalesopportunitiesconflicts',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectstosalesopportunitiesconflicts',
            name='salesOpportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productMarketing.salesopportunities'),
        ),
    ]
