# Generated by Django 3.2.16 on 2023-02-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('productMarketing', '0004_auto_20230214_0332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currencies',
            new_name='CurrenciesArchive',
        ),
        migrations.RenameModel(
            old_name='ExchangeRates',
            new_name='ExchangeRatesArchive',
        ),
        migrations.AlterField(
            model_name='vhkcy',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
    ]
