# Generated by Django 3.2.16 on 2023-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importExport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploading',
            name='docfile',
            field=models.FileField(default='f.pdf', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
