# Generated by Django 3.2.16 on 2023-01-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_dummycustomerexceptionproductfamilies_exceptedfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesname',
            name='valid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
