# Generated by Django 3.2.16 on 2023-01-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20230128_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdetail',
            name='appLine',
        ),
    ]
