# Generated by Django 3.2.16 on 2023-01-28 04:00

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20230128_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicationLine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.applicationline', verbose_name='Application Line'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applicationDetail',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='applicationMain', chained_model_field='appMain', null=True, on_delete=django.db.models.deletion.PROTECT, to='project.applicationdetail', verbose_name='Application Detail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applicationMain',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='applicationLine', chained_model_field='appLine', null=True, on_delete=django.db.models.deletion.PROTECT, to='project.applicationmain', verbose_name='Application Main'),
        ),
    ]
