# Generated by Django 3.2.16 on 2023-01-31 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20230128_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('dragonCodes', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
