# Generated by Django 3.2.16 on 2023-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_todoitems'),
    ]

    """

            migrations.AddField(
            model_name='project',
            name='syntheticProjectName',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='SyntheticProjectName'),
        ),

    """




