# Generated by Django 3.2.16 on 2023-02-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_syntheticprojectname'),
    ]
    """
    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_together_project',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('mainCustomer', 'finalCustomer', 'draft', 'productMarketer', 'applicationDetail', 'applicationMain', 'sales_name', 'dummy', 'syntheticProjectName'), name='unique_together_project'),
        ),
    ]
    """
