# Generated by Django 3.2.16 on 2023-02-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_contractualcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetail',
            name='appDetailDescription',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='applicationline',
            name='applicationLineLongName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='applicationline',
            name='applicationLineShortName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='statusDisplay',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
