# Generated by Django 3.2.16 on 2023-02-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20230214_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='salesNameDefaulted',
            field=models.BooleanField(default=True),
        ),
    ]
