# Generated by Django 3.2.16 on 2023-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_salesnamedefaulted'),
        ('project', '0015_missingsalesplan_salesplanwithnoproject'),
    ]

    operations = [
    ]
