# Generated by Django 3.2.16 on 2023-02-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0006_auto_20230130_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='boup',
            name='endCustomerHelper',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boup',
            name='mainCustomerHelper',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
