# Generated by Django 3.2.16 on 2023-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0007_auto_20230205_1807'),
    ]
    """
    operations = [
        migrations.AddField(
            model_name='boup',
            name='syntheticProjectName',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='SyntheticProjectName'),
        ),
    ]
    """
