# Generated by Django 3.2.16 on 2023-02-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0008_boup_syntheticprojectname'),
    ]

    """
    operations = [
        migrations.RemoveConstraint(
            model_name='boup',
            name='unique_together_project_boup',
        ),
        migrations.AddConstraint(
            model_name='boup',
            constraint=models.UniqueConstraint(fields=('mainCustomer', 'endCustomer', 'applicationDetail', 'applicationMain', 'salesName', 'syntheticProjectName'), name='unique_together_project_boup'),
        ),
    ]
    """
