# Generated by Django 3.2.16 on 2023-02-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0009_auto_20230210_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='boup',
            name='contractualCurrency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('JPY', 'JPY'), ('MXN', 'MXN'), ('CHF', 'CHF')], default='USD', max_length=3, null=True),
        ),
    ]
