# Generated by Django 3.2.16 on 2023-02-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0010_boup_contractualcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boup',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('JPY', 'JPY'), ('MXN', 'MXN'), ('CHF', 'CHF')], default='USD', max_length=3, null=True),
        ),
    ]
