# Generated by Django 3.2.16 on 2023-02-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0011_alter_boup_currency'),
        ('productMarketingDwh', '0011_auto_20230214_1905'),
    ]

    operations = [
    ]
