# Generated by Django 3.2.16 on 2023-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0011_alter_boup_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boup',
            name='statusProbability',
            field=models.CharField(default='fieldMissing', max_length=40),
        ),
    ]
