# Generated by Django 3.2.16 on 2023-02-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0012_merge_20230222_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boup',
            name='contractualCurrency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('JPY', 'JPY'), ('MXN', 'MXN'), ('CHF', 'CHF')], default='EUR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='boup',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('JPY', 'JPY'), ('MXN', 'MXN'), ('CHF', 'CHF')], default='EUR', max_length=3, null=True),
        ),
    ]
