# Generated by Django 3.2.16 on 2023-02-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0012_alter_boup_statusprobability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boup',
            name='ecHlp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='boup',
            name='mcHlp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='boup',
            name='rfpHlp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
