# Generated by Django 3.2.16 on 2023-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0014_auto_20230223_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='boup',
            name='plHfg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='boup',
            name='region',
            field=models.CharField(choices=[('EMEA', 'EMEA'), ('AMERICAS', 'AMERICAS'), ('AP', 'AP'), ('JAPAN', 'JAPAN'), ('GC', 'GC'), ('MISC', 'MISC')], default='EMEA', max_length=10),
        ),
    ]
