# Generated by Django 3.2.16 on 2023-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productMarketingDwh', '0013_auto_20230222_0317'),
        ('productMarketingDwh', '0015_auto_20230223_1940'),
    ]

    operations = [
    ]
